# Generated by Django 6.0.4 on 2026-04-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Magoreal Tecnología', max_length=80, verbose_name='Nombre del sitio')),
                ('tagline', models.CharField(default='Automatización real + IA + Django a medida.', help_text='Frase de una línea usada en meta tags y footer', max_length=160, verbose_name='Slogan corto')),
                ('hero_title', models.TextField(default='Automatización real + IA + Django a medida.\nTodo corriendo en tu propia infraestructura.', help_text='Soporta saltos de línea. Se renderiza con <br>.', verbose_name='Título del hero')),
                ('hero_subtitle', models.TextField(default='Ayudo a empresas de Bolivia y la región a reemplazar SaaS caros, conectar sus procesos internos con IA y desplegar sistemas web hechos a medida — sin mensualidades por usuario y sin datos afuera.', verbose_name='Subtítulo del hero')),
                ('logo_svg', models.TextField(blank=True, default='<svg viewBox="0 0 210 40" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Magoreal">\n  <text x="0"  y="30" font-family="Inter, system-ui, sans-serif" font-weight="800" font-size="26" fill="#38BDF8">&lt;</text>\n  <text x="14" y="30" font-family="Inter, system-ui, sans-serif" font-weight="800" font-size="26" fill="#FFFFFF">M</text>\n  <text x="32" y="30" font-family="Inter, system-ui, sans-serif" font-weight="800" font-size="26" fill="#38BDF8">/&gt;</text>\n  <text x="60" y="30" font-family="Inter, system-ui, sans-serif" font-weight="700" font-size="22" fill="#FFFFFF" letter-spacing="-0.5">magoreal</text>\n  <circle cx="200" cy="26" r="3" fill="#4ADE80"/>\n</svg>', help_text='Código SVG completo del logo. Se renderiza inline.', verbose_name='Logo SVG')),
                ('email', models.EmailField(default='magoreal4@gmail.com', max_length=254, verbose_name='Email de contacto')),
                ('phone', models.CharField(blank=True, help_text='Formato con país, ej: +591 7X XXX XXXX', max_length=30, verbose_name='Teléfono')),
                ('whatsapp_number', models.CharField(blank=True, help_text="Formato E.164 sin el '+', ej: 59170000000", max_length=30, verbose_name='Número de WhatsApp')),
                ('calendar_url', models.URLField(blank=True, help_text='Link Cal.com, Calendly o similar para agendar llamadas', verbose_name='URL de calendario')),
                ('city', models.CharField(default='Santa Cruz de la Sierra, Bolivia', max_length=80, verbose_name='Ciudad / ubicación')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('scripts_head', models.TextField(blank=True, help_text='HTML inyectado en <head>. Usar para verificación de Search Console, meta tags custom, etc. Se renderiza con |safe.', verbose_name='Scripts en <head>')),
                ('scripts_body_start', models.TextField(blank=True, help_text='Ideal para Google Tag Manager. Se renderiza con |safe.', verbose_name='Scripts al inicio de <body>')),
                ('scripts_body_end', models.TextField(blank=True, help_text='Ideal para Plausible, Umami, Facebook Pixel, AdSense. Se renderiza con |safe.', verbose_name='Scripts al final de <body>')),
                ('n8n_translate_webhook', models.URLField(blank=True, help_text='URL del webhook n8n que orquesta la traducción con OpenAI', verbose_name='Webhook n8n para traducción')),
                ('available_languages', models.CharField(default='es,en', help_text='Códigos ISO separados por coma. Ejemplo: es,en,pt', max_length=60, verbose_name='Idiomas disponibles')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
