# Generated by Django 6.0.4 on 2026-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='city',
            field=models.CharField(default='Santa Cruz de la Sierra', max_length=80, verbose_name='Ciudad / ubicación'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_subtitle',
            field=models.TextField(default='Ayudamos a empresas de Latinoamérica y más allá a reemplazar servicios mensuales caros y desplegar sistemas con IA en su propio sistema — sin cobros por usuario, sin datos afuera.', verbose_name='Subtítulo del hero'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_title',
            field=models.TextField(default='Automatizamos tus procesos con IA.\nEn tu propio sistema, sin cobros por usuario.', help_text='Soporta saltos de línea. Se renderiza con <br>.', verbose_name='Título del hero'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(default='Automatizamos tus procesos con IA. En tu propio sistema.', help_text='Frase de una línea usada en meta tags y footer', max_length=160, verbose_name='Slogan corto'),
        ),
    ]
