# Generated by Django 6.0.4 on 2026-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_alter_siteconfig_city_alter_siteconfig_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contacto_webhook_secret',
            field=models.CharField(blank=True, help_text='Django envía X-Webhook-Secret con este valor al webhook n8n. El workflow n8n valida que coincida antes de procesar. Dejar vacío desactiva el reenvío — el mensaje solo se guarda en DB.', max_length=80, verbose_name='Shared secret para webhook de contacto'),
        ),
    ]
