# Generated by Django 6.0.3 on 2026-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0012_siteconfig_privacy_terms_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único. Ej: cliente-a', unique=True, verbose_name='Slug')),
                ('domain', models.CharField(blank=True, db_index=True, help_text='Dominio o subdominio que activa esta página. Ej: cliente.magoreal.com', max_length=255, verbose_name='Dominio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, help_text='Si no hay coincidencia de dominio, usar esta página. Solo una puede ser default.', verbose_name='Por defecto')),
                ('site_name', models.CharField(default='', max_length=80, verbose_name='Nombre del sitio')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='Slogan corto')),
                ('hero_title', models.TextField(blank=True, help_text='Soporta saltos de línea. Se renderiza con <br>.', verbose_name='Título del hero')),
                ('hero_subtitle', models.TextField(blank=True, help_text='Cada salto de línea genera un párrafo separado.', verbose_name='Subtítulo del hero')),
                ('logo_svg', models.TextField(blank=True, help_text='Código SVG completo del logo. Vacío = usa el de SiteConfig.', verbose_name='Logo SVG')),
                ('theme', models.CharField(choices=[('tron', 'Tron (Cyan)'), ('ares', 'Ares (Red)'), ('clu', 'Clu (Orange)'), ('athena', 'Athena (Gold)'), ('aphrodite', 'Aphrodite (Pink)'), ('poseidon', 'Poseidon (Blue)')], default='tron', max_length=20, verbose_name='Tema visual')),
                ('default_language', models.CharField(default='es', help_text='Código ISO. Ej: es, en, pt', max_length=5, verbose_name='Idioma por defecto')),
                ('theme_color', models.CharField(default='#050A14', help_text='Color para <meta name="theme-color"> y móviles.', max_length=7, verbose_name='Theme color (meta tag)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto público')),
                ('phone', models.CharField(blank=True, help_text='Formato con país, ej: +591 7X XXX XXXX', max_length=30, verbose_name='Teléfono')),
                ('whatsapp_number', models.CharField(blank=True, help_text="Formato E.164 sin el '+', ej: 59170000000", max_length=30, verbose_name='Número de WhatsApp')),
                ('calendar_url', models.URLField(blank=True, help_text='Link Cal.com, Calendly o similar para agendar llamadas', verbose_name='URL de calendario')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ciudad / ubicación')),
                ('privacy_policy_url', models.URLField(blank=True, verbose_name='URL política de privacidad')),
                ('terms_url', models.URLField(blank=True, verbose_name='URL términos y condiciones')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('scripts_head', models.TextField(blank=True, help_text='HTML inyectado en <head>. Se renderiza con |safe.', verbose_name='Scripts en <head>')),
                ('scripts_body_start', models.TextField(blank=True, help_text='Ideal para Google Tag Manager. Se renderiza con |safe.', verbose_name='Scripts al inicio de <body>')),
                ('scripts_body_end', models.TextField(blank=True, help_text='Ideal para Plausible, Umami, Pixel. Se renderiza con |safe.', verbose_name='Scripts al final de <body>')),
                ('n8n_translate_webhook', models.URLField(blank=True, verbose_name='Webhook n8n para traducción')),
                ('available_languages', models.CharField(default='es,en', help_text='Códigos ISO separados por coma. Ejemplo: es,en,pt', max_length=60, verbose_name='Idiomas disponibles')),
                ('contacto_webhook_secret', models.CharField(blank=True, max_length=80, verbose_name='Shared secret para webhook de contacto')),
                ('pliego_demo_webhook_secret', models.CharField(blank=True, max_length=80, verbose_name='Shared secret para webhook de demo de pliego')),
                ('favicon', models.ImageField(blank=True, upload_to='site_favicons/', verbose_name='Favicon')),
                ('og_image', models.ImageField(blank=True, help_text='1200x630 recomendado. Se usa para og:image y Twitter Card.', upload_to='site_og/', verbose_name='Imagen Open Graph')),
            ],
            options={
                'verbose_name': 'Página de cliente',
                'verbose_name_plural': 'Páginas de clientes',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_sitepage_default')],
            },
        ),
    ]
