# Generated by Django 6.0.4 on 2026-04-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0013_sitepage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sitepage',
            name='unique_sitepage_default',
        ),
    ]
