# Generated by Django 6.0.4 on 2026-04-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0014_remove_sitepage_unique_sitepage_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_svg',
            field=models.TextField(blank=True, default='<svg viewBox="0 0 58 40" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Magoreal">\n  <text x="0"  y="30" font-family="Inter, system-ui, sans-serif" font-weight="800" font-size="26" fill="#38BDF8">&lt;</text>\n  <text x="14" y="30" font-family="Inter, system-ui, sans-serif" font-weight="800" font-size="26" fill="#FFFFFF">M</text>\n  <text x="32" y="30" font-family="Inter, system-ui, sans-serif" font-weight="800" font-size="26" fill="#38BDF8">/&gt;</text>\n</svg>', help_text='Código SVG completo del logo. Se renderiza inline.', verbose_name='Logo SVG'),
        ),
    ]
