# Generated by Django 6.0.4 on 2026-04-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0015_alter_siteconfig_logo_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='sk-... Se almacena en la base de datos.', max_length=200, verbose_name='OpenAI API Key'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='openai_model',
            field=models.CharField(blank=True, default='gpt-4.1-mini', help_text='Ejemplos: gpt-4.1-mini, gpt-4o, gpt-4o-mini, gpt-4.1', max_length=60, verbose_name='Modelo OpenAI'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='n8n_translate_webhook',
            field=models.URLField(blank=True, help_text='Ya no se usa si openai_api_key está configurado.', verbose_name='Webhook n8n (legado)'),
        ),
    ]
