# Generated by Django 6.0.4 on 2026-05-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0016_openai_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='multilingual',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no se muestra el selector de idioma en el menú.', verbose_name='Multilenguaje activo'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='multilingual',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no se muestra el selector de idioma en el menú.', verbose_name='Multilenguaje activo'),
        ),
    ]
