# Generated by Django 6.0.4 on 2026-05-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0017_add_multilingual_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='n8n_translate_webhook',
        ),
        migrations.RemoveField(
            model_name='sitepage',
            name='n8n_translate_webhook',
        ),
    ]
