# Generated by Django 6.0.3 on 2026-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0018_remove_n8n_translate_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='SVG, PNG o ICO. Vacío = usa /static/img/favicon.svg', upload_to='site_favicons/', verbose_name='Favicon'),
        ),
    ]
