# Generated by Django 6.0.4 on 2026-05-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0019_add_favicon_to_siteconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='openai_model',
        ),
    ]