# Generated by Django 6.0.4 on 2026-04-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=120)),
                ('interes', models.CharField(choices=[('web', 'Desarrollo web a medida'), ('ia', 'Automatización con IA'), ('infra', 'Infraestructura self-hosted'), ('chat', 'Integraciones & chatbots'), ('otro', 'Otro / no estoy seguro')], default='otro', max_length=10)),
                ('mensaje', models.TextField(max_length=2000)),
                ('meta_origen', models.CharField(blank=True, help_text='Path de la página desde donde se envió', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_n8n', models.BooleanField(default=False, help_text='True si el webhook n8n respondió 2xx')),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-creado_en'],
            },
        ),
    ]
