# Generated by Django 6.0.3 on 2026-04-28 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_pliegodemolead'),
        ('site_config', '0013_sitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='sitepage',
            field=models.ForeignKey(blank=True, help_text='SitePage desde donde se envió el mensaje (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_config.sitepage', verbose_name='Página de origen'),
        ),
        migrations.AddField(
            model_name='pliegodemolead',
            name='sitepage',
            field=models.ForeignKey(blank=True, help_text='SitePage desde donde se envió el lead (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_config.sitepage', verbose_name='Página de origen'),
        ),
    ]
