# Generated by Django 6.0.4 on 2026-05-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MorphConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='MAGOREAL', help_text='Palabra que se mostrar en el banner morph (ej: MAGOREAL)', max_length=50, verbose_name='Palabra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Morph Banner',
                'verbose_name_plural': 'Morph Banner',
            },
        ),
    ]
