# Generated by Django 6.0.3 on 2026-05-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph_banner', '0001_initial'),
        ('site_config', '0016_openai_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorphBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='MAGOREAL', help_text='Palabra que se mostrará en el banner morph (ej: MAGOREAL)', max_length=50, verbose_name='Palabra')),
                ('letter_colors', models.JSONField(blank=True, default=dict, help_text='JSON con colores por letra. Ej: {"A": "#FF0000", "M": "accent"}. Valores: hex (#RRGGBB) o paleta (primary, secondary, accent, info, success, warning, error, neutral). Default: primary para todas.', verbose_name='Colores por letra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sitepage', models.OneToOneField(blank=True, help_text='Vacío = sitio principal (Magoreal). Solo uno por sitio.', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_config.sitepage', verbose_name='Página del sitio')),
            ],
            options={
                'verbose_name': 'Morph Banner',
                'verbose_name_plural': 'Morph Banners',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='MorphConfig',
        ),
    ]
