# Generated by Django 6.0.3 on 2026-05-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph_banner', '0003_morphbanner_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphbanner',
            name='letter_colors',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con un color por cada carácter distinto de la palabra (A–Z, a–z, 0–9). Las mayúsculas y minúsculas comparten el mismo color (clave en mayúscula). Ej: {"A": "#FF0000", "M": "accent", "8": "warning"}. Valores: hex (#RRGGBB) o paleta (primary, secondary, accent, info, success, warning, error, neutral). Si no definís un carácter, usa primary.', verbose_name='Colores por carácter'),
        ),
    ]
