# Generated by Django 6.0.4 on 2026-05-03 22:25

import landing.morph_banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph_banner', '0005_letter_colors_list_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphbanner',
            name='letter_colors',
            field=models.JSONField(blank=True, default=landing.morph_banner.models.letter_colors_default, help_text='Lista JSON ordenada por cada glifo renderizado en la palabra (espacios y símbolos sin fuente morph se omiten): ["primary","accent","#3366CC", …]. Índice 0 = primera letra visible, etc.; dos letras repetidas pueden tener dos colores distintos. Formatos legacy tipo {"M":"accent"} siguen funcionando hasta que guardes desde el admin. Valores: paleta (primary…) o hex #RRGGBB.', verbose_name='Colores por posición'),
        ),
    ]
