# Generated by Django 6.0.4 on 2026-05-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph_banner', '0007_morphbanner_neon_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphbanner',
            name='word',
            field=models.CharField(default='MAGOREAL', help_text='Texto morph (solo A–Z, a–z, 0–9 y espacios). Cada espacio deja hueco horizontal entre grupos de letras.', max_length=50, verbose_name='Palabra'),
        ),
    ]
