# Generated by Django 6.0.4 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_translator', '0002_translatorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatorconfig',
            name='available_languages',
            field=models.JSONField(blank=True, default=['en', 'pt', 'fr', 'de', 'it'], help_text='Lista JSON de códigos ISO de dos letras, ej: ["en", "pt", "fr", "de", "it"]. Idioma base (es) no se incluye aquí.', verbose_name='Idiomas disponibles'),
        ),
    ]